Example.Web/Controllers/SmellerController.cs
using ScrapeIT.Framework.Business.Interface;
using ScrapeIT.Framework.Business.Repository;
using ScrapeIT.Framework.Scraper.Smeller;
using ScrapeIT.Framework.Scraper.Tabelar;

namespace Example.Web.Controllers
{
    public class SmellerController : ScrapeIT.Web.Mvc.Controllers.SmellerControlerBase
    {
        public SmellerController(SmellerFactory smellerFactory, PageRepository pageRepository, ScrapeRepository scrapeRepository, TabelarFactory tabelarFactory, ICustomerContext customerContext) : base(smellerFactory, pageRepository, scrapeRepository, tabelarFactory, customerContext)
        {
        }
    }
}

Example.Web/Controllers/TabelarController.cs
using ScrapeIT.Framework.Business.Interface;
using ScrapeIT.Framework.Business.Repository;
using ScrapeIT.Framework.Scraper.Tabelar;
using ScrapeIT.Web.Mvc.Controllers;

namespace Example.Web.Controllers
{
    public class TabelarController : TabelarControllerBase
    {
        public TabelarController(ScrapeRepository scrapeRepository, TabelarFactory tabelarFactory, ICustomerContext customerContext) : base(scrapeRepository, tabelarFactory, customerContext)
        {
        }
    }
}

Example.Web/Views/Smeller/ExecuteSmellerTest.cshtml
@model ScrapeIT.Web.Mvc.Models.ExecuteSmellerModel

@{
    ViewBag.Title = "ExecuteSmellerTest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="jumbotron">
    <h1>Page is</h1>
    <p class="lead">
        @if (Model.IsSmelly)
         {
        <b>Smelly!!</b>
        }
        else
        {
            <b>Not smelly</b>
        }
    </p>
    <p></p>
</div>

<div class="row">
    <div class="col-md-4">
       
        @Html.ActionLink("Execute tabular", "ExecuteTablearTest", "Tabelar", new { address = Model.Address }, null)
    </div>
</div>

Example.Web/Views/Smeller/SmellerTest.cshtml
@{
    ViewBag.Title = "SmellerTest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SmellerTest</h2>


<section>
    @using (Html.BeginForm("ExecuteSmellerTest", "Smeller"))
    {
        <p>Voer een smeller uit.</p>
        @Html.TextBox("address", "", new { placeholder = "Scrape url" })
        <input type="submit" value="Smell" />
    }
</section>