Example.Web/Controllers/BlobController.cs
using Microsoft.AspNetCore.Mvc;
using ScrapeIT.Framework.Business.Interface;
using ScrapeIT.Framework.Business.Repository;
using ScrapeIT.Framework.CloudUtilities;
using ScrapeIT.Framework.Scraper.Tabelar;

namespace Example.Web.Controllers
{
    public class BlobController : ScrapeIT.Web.Mvc.Controllers.BlobControllerBase
    {
        public BlobController(IBlobStorage blobStorage, ScrapeRepository scrapeRepository, TabelarFactory tabelarFactory, ICustomerContext customerContext) : base(blobStorage, scrapeRepository, tabelarFactory, customerContext)
        {
        }


        // GET: Blob
        public ActionResult Index()
        {
            return View();
        }
    }
}

Example.Web/Controllers/GraphController.cs
using ScrapeIT.Framework.Business.Interface;
using ScrapeIT.Framework.Business.Repository;
using ScrapeIT.Framework.Scraper.Tabelar;

namespace Example.Web.Web.Controllers
{
    public class GraphController : ScrapeIT.Web.Mvc.Controllers.GraphControllerBase
    {
        public GraphController(PageRepository pageRepository, ScrapeRepository scrapeRepository, TabelarFactory tabelarFactory, ICustomerContext customerContext) : base(pageRepository, scrapeRepository, tabelarFactory, customerContext)
        {
        }
    }
}

Example.Web/Controllers/HomeController.cs
using ScrapeIT.Framework.Business.Interface;
using ScrapeIT.Framework.Business.Repository;

namespace Example.Web.Controllers
{
    public class HomeController : ScrapeIT.Web.Mvc.Controllers.HomeControllerBase
    {
        public HomeController(ICustomerContext customrContext, ScrapeIT.Framework.CloudUtilities.Startup startup) : base(customrContext, startup)
        {
        }
    }
}

Example.Web/Controllers/PathController.cs
using ScrapeIT.Framework.Business.Interface;
using ScrapeIT.Framework.Business.Repository;
using ScrapeIT.Framework.Scraper.Contexts;
using ScrapeIT.Framework.Scraper.Processors;
using ScrapeIT.Framework.Scraper.Tabelar;
using ScrapeIT.FunctionApp.Handlers;

namespace Example.Web.Controllers
{
    public class PathController : ScrapeIT.Web.Mvc.Controllers.PathControllerBase
    {
        public PathController(ScrapeHandler<ScrapeContext> scrapeHandler, ReProcessor reProcessor, PageRepository pageRepository, ScrapeRepository scrapeRepository, TabelarFactory tabelarFactory, ICustomerContext customerContext) : base(scrapeHandler, reProcessor, pageRepository, scrapeRepository, tabelarFactory, customerContext)
        {
        }

    }
}

Example.Web/Controllers/QueueController.cs
using Microsoft.AspNetCore.Mvc;
using ScrapeIT.Framework.Business.Interface;
using ScrapeIT.Framework.Business.Repository;
using ScrapeIT.Framework.CloudUtilities.MessageBus;
using ScrapeIT.Framework.Scraper.Tabelar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Example.Web.Controllers
{
    public class QueueController : ScrapeIT.Web.Mvc.Controllers.QueueControllerBase
    {
        public QueueController(QueueFactory queueFactory, TopicFactory topicFactory, ScrapeIT.Framework.CloudUtilities.Startup startup, ScrapeRepository scrapeRepository, TabelarFactory tabelarFactory, ICustomerContext customerContext) : base(queueFactory, topicFactory, startup, scrapeRepository, tabelarFactory, customerContext)
        {
        }
    }
}

Example.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Example.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Leidse rijn 35<br />
    Utrecht, 3454 PZ De Meern<br />
    <abbr title="Phone">P:</abbr>
    030-7371101
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:gertjan@scrape-it.nl">gertjan@scrape-it.nl</a><br />
    <strong>Sales:</strong> <a href="mailto:roland@scrape-it.nl">roland@scrape-it.nl</a>
</address>

Example.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Sites.Web</h1>
    <p class="lead">Home</p>
    <p></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Test</h2>
        <p>
            <ul>
                <li>@Html.ActionLink("Blob test", "Index", "Blob")</li>
                <li>@Html.ActionLink("Smeller test", "SmellerTest", "Smeller")</li>
                <li>@Html.ActionLink("UrlExtractor test", "Index", "Extractor")</li>
                <li>@Html.ActionLink("Tabelar test", "TabelarTest", "Tabelar")</li>
                <li>@Html.ActionLink("Mapping test", "MapTest", "Mappings")</li>
                <li>@Html.ActionLink("Save mapping test", "SaveMapTest", "Mappings")</li>
                <li>@Html.ActionLink("Graph test", "Index", "Graph")</li>
                <li>@Html.ActionLink("Path test", "ScrapePathTest", "Path")</li>
            </ul>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>
            <ul>
                <li>@Html.ActionLink("Mappings", "MapManual", "Mappings")</li>
                <li>@Html.ActionLink("View mappings", "ViewMappingsPerDomain", "Mappings")</li>
                <li>@Html.ActionLink("Export", "Index", "Export")</li>
                <li>@Html.ActionLink("Convert", "Index", "Convert")</li>
                <li>@Html.ActionLink("Restore scrape dead queues", "ScrapeQueuesFromDeadQueuesAsync", "Queue")</li>
            </ul>

        </p>
        <p></p>
    </div>
    <div class="col-md-4">
        <h2>Customer</h2>
        <p>
            <ul>
                <li>@Html.ActionLink("Page count", "Index", "Check")</li>                
            </ul>
        </p>
        <p></p>
    </div>

</div>