Example.Web/Controllers/GraphController.cs
using ScrapeIT.Framework.Business.Interface;
using ScrapeIT.Framework.Business.Repository;
using ScrapeIT.Framework.Scraper.Tabelar;

namespace Example.Web.Web.Controllers
{
    public class GraphController : ScrapeIT.Web.Mvc.Controllers.GraphControllerBase
    {
        public GraphController(PageRepository pageRepository, ScrapeRepository scrapeRepository, TabelarFactory tabelarFactory, ICustomerContext customerContext) : base(pageRepository, scrapeRepository, tabelarFactory, customerContext)
        {
        }
    }
}

Example.Web/Controllers/TabelarController.cs
using ScrapeIT.Framework.Business.Interface;
using ScrapeIT.Framework.Business.Repository;
using ScrapeIT.Framework.Scraper.Tabelar;
using ScrapeIT.Web.Mvc.Controllers;

namespace Example.Web.Controllers
{
    public class TabelarController : TabelarControllerBase
    {
        public TabelarController(ScrapeRepository scrapeRepository, TabelarFactory tabelarFactory, ICustomerContext customerContext) : base(scrapeRepository, tabelarFactory, customerContext)
        {
        }
    }
}

Example.Web/Views/Graph/CheckUrl.cshtml
@model ScrapeIT.Web.Mvc.Models.Graph.GraphNodeModel

@{
    ViewBag.Title = "CheckUrl";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CheckUrl</h2>

<section>
    <h2>Scrape</h2>
    <table>
        <tr>
            <th>Url</th>
            <td>
                @Model.Url
                @Html.ActionLink("<Run tabelar>", "ExecuteTabelarTest", "Tabelar", new { address = Model.Url, previous=Model.PreviousUrl }, null)
            </td>
        </tr>
        <tr>
            <th>Previous Url</th>
            <td>
                @if (Model.PreviousUrl != null)
                {
                    @Html.ActionLink(Model.PreviousUrl, "CheckUrl", "Graph", new { address = Model.PreviousUrl }, null)
                    @Html.ActionLink("<Run tabelar>", "ExecuteTabelarTest", "Tabelar", new { address = Model.PreviousUrl }, null)
                }
            </td>
        </tr>
        <tr>
            <th>ScrapeDate</th>
            <td>@Model.Scrape.ScrapeDate</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>@Model.Scrape.StatusCode</td>
        </tr>
        <tr>
            <th>Media type</th>
            <td>@Model.Scrape.MediaType</td>
        </tr>
        <tr>
            <th>Expiration date</th>
            <td>@Model.Scrape.ExpirationDate</td>
        </tr>

    </table>
</section>

<section>
    <h2>Children</h2>

    <ul style="list-style-type:square !important; margin-left: 15px;">
        @foreach (var child in Model.ChildPages)
        {
            <li>@Html.ActionLink(child.Url, "CheckUrl", "Graph", new { address = child.Url }, null)</li>
            @*&nbsp;@Html.ActionLink("<Run tabelar>", "ExecuteTablearTest", "Scraper", new { address = urlFromModel.ToString() }, null)*@
        }
    </ul>
</section>

Example.Web/Views/Graph/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Start with graph url</h2>


<section>
    @using (Html.BeginForm("CheckUrl", "Graph"))
    {
        <p>Check this url for scrape information.</p>
        <label>Before: <input type="date" name="beforeDate" /></label>
        @Html.TextBox("address", "", new { placeholder = "Scrape url" })
        <input type="submit" value="Check" />
    }
</section>

<section>
    @using (Html.BeginForm("CleanUrl", "Graph"))
    {
        <p>Clean scrapes including child pages.</p>
        @Html.TextBox("address", "", new { placeholder = "Scrape url" })
        <input type="submit" value="Clean" />
    }
</section>

<section>
    @using (Html.BeginForm("CleanSingleUrl", "Graph"))
    {
        <p>Clean scrape, not child pages.</p>
        @Html.TextBox("address", "", new { placeholder = "Scrape url" })
        <input type="submit" value="Clean" />
    }
</section>