Example.Web/Controllers/ExtractorController.cs
using ScrapeIT.Framework.Business.Interface;
using ScrapeIT.Framework.Business.Repository;
using ScrapeIT.Framework.CloudUtilities.MessageBus;
using ScrapeIT.Framework.Scraper.Tabelar;
using ScrapeIT.Framework.Scraper.UrlExtractor;
using ScrapeIT.Web.Mvc.Controllers;

namespace Example.Web.Controllers
{
    public class ExtractorController : ExtractorControllerBase
    {
        public ExtractorController(QueueFactory queueFactory, ExtractorFactory extractorFactory, ScrapeRepository scrapeRepository, TabelarFactory tabelarFactory, ICustomerContext customerContext) : base(queueFactory, extractorFactory, scrapeRepository, tabelarFactory, customerContext)
        {
        }
    }
}

Example.Web/Controllers/TabelarController.cs
using ScrapeIT.Framework.Business.Interface;
using ScrapeIT.Framework.Business.Repository;
using ScrapeIT.Framework.Scraper.Tabelar;
using ScrapeIT.Web.Mvc.Controllers;

namespace Example.Web.Controllers
{
    public class TabelarController : TabelarControllerBase
    {
        public TabelarController(ScrapeRepository scrapeRepository, TabelarFactory tabelarFactory, ICustomerContext customerContext) : base(scrapeRepository, tabelarFactory, customerContext)
        {
        }
    }
}

Example.Web/Views/Extractor/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Extractor tests</h1>

<li>@Html.ActionLink("UrlExtractor test", "UrlExtractorTest", "Extractor")</li>
<li>@Html.ActionLink("ReExtractor", "UrlExtractorTest", "Extractor")</li>



<section>
    @using (Html.BeginForm("ReExtract", "Extractor"))
    {
    <p>Do a reextract for this url and its children</p>
    @Html.TextBox("address", "", new { placeholder = "reextract url" })
    <input type="submit" value="Check" />
    }
</section>

Example.Web/Views/Extractor/UrlExtractorTest.cshtml
@model List<ScrapeIT.Framework.Scraper.UrlExtractor.ExtractorRequest>  
@{
    ViewBag.Title = "URL-extractortest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>URL-extractortest</h1>

<section>
    @using (Html.BeginForm("ExecuteUrlExtractorTest", "Extractor"))
    {
        <p>Voer een URL-extractietest uit. @*Voer hier de URL in:*@</p>
        @Html.TextBox("address", "", new { placeholder = "www.naamvanwebsite.extensie", style = "width:600px" })
        <br/>
        @Html.TextBox("correlationID", "", new { placeholder = "Correlatie id (optioneel)" })
        <input type="submit" value="Extract" />
    }
</section>

<section class="output-extractortest">
    <br />
    <h2>Output</h2>
    <ul style="list-style-type:square !important; margin-left: 15px;">
        @foreach (var extractFromModel in Model)
        {
            <li>
                @Html.ActionLink(extractFromModel.ToString(), "ExecuteUrlExtractorTest", "Extractor", new { address= extractFromModel.Uri.ToString()}, null)&nbsp;@Html.ActionLink("<Run tabelar>" , "ExecuteTabelarTest", "Tabelar", new { address = extractFromModel.Uri.ToString() }, null)
                @if(extractFromModel.RequestType == ScrapeIT.Framework.Messaging.Messages.WebMethod.Post)
                {
                    <div>
                        <span>(post)</span>
                        <span>@extractFromModel.Body</span>
                    </div>
                }

            </li>            
        }
    </ul>
</section>